import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bell,ChevronDown,Gift,Home,Menu,Play,PlayCircle,Trophy,UserRound,X,CheckCircle2,Clock3,LoaderCircle,ShieldCheck,Plus,Users,Flame,WalletCards,Target,Medal,ArrowUpRight,Star,LockKeyhole,Phone,Mail,Send,BadgeCheck,CalendarDays,Info,Shield,ClipboardCheck,ListChecks,HelpCircle,Settings,LogOut,History,IndianRupee,RefreshCw} from 'lucide-react';
import './styles.css';

const ADS=[
{id:'a1',brand:'boAt',title:'Discover boAt audio',duration:30,reward:20,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80'},
{id:'a2',brand:'Samsung',title:'Explore smart technology',duration:25,reward:25,image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80'},
{id:'a3',brand:'Amazon',title:'Find something you love',duration:20,reward:15,image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80'},
{id:'a4',brand:'Nike',title:'Move with purpose',duration:35,reward:30,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80'},
{id:'a5',brand:'Netflix',title:'Your next story awaits',duration:25,reward:20,image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80'},
{id:'a6',brand:'Zomato',title:'Discover your next meal',duration:30,reward:25,image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=900&q=80'},
{id:'a7',brand:'Spotify',title:'Tune into your day',duration:20,reward:18,image:'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=80'},
{id:'a8',brand:'Flipkart',title:'Shop your favourites',duration:25,reward:22,image:'https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&w=900&q=80'},
{id:'a9',brand:'Myntra',title:'Refresh your style',duration:30,reward:28,image:'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80'},
{id:'a10',brand:'Adobe',title:'Create without limits',duration:35,reward:35,image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80'}
];
const KEY='veloop-v2';
const defaultState={balance:2450,watched:[],history:[],streak:7,claims:0,giveawayEntries:[],lastDay:new Date().toDateString()};
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaultState}}
function App(){
 const [state,setState]=useState(load); const [page,setPage]=useState('dashboard'); const [menu,setMenu]=useState(false); const [activeAd,setActiveAd]=useState(null); const [time,setTime]=useState(0); const [toast,setToast]=useState(''); const [showGiveaway,setShowGiveaway]=useState(false); const [form,setForm]=useState({name:'',phone:'',email:'',address:''});
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(state)),[state]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{if(activeAd===null)return; if(time<=0)return; const t=setInterval(()=>setTime(x=>x-1),1000); return()=>clearInterval(t)},[activeAd,time]);
 useEffect(()=>{if(activeAd!==null&&time===0){const ad=ADS.find(x=>x.id===activeAd);if(ad&&!state.watched.includes(ad.id)){setState(s=>({...s,balance:s.balance+ad.reward,watched:[...s.watched,ad.id],history:[{id:Date.now(),text:`${ad.brand} ad completed`,amount:ad.reward,date:new Date().toLocaleString()},...s.history]}));setToast(`+${ad.reward} VE added to your wallet`);setActiveAd(null)}}},[time,activeAd]);
 const earnedToday=useMemo(()=>state.history.filter(h=>new Date(h.date).toDateString()===new Date().toDateString()).reduce((a,h)=>a+h.amount,0),[state.history]);
 const progress=Math.min(state.watched.length,10); const remaining=ADS.filter(a=>!state.watched.includes(a.id));
 const nav=[['dashboard','Dashboard',Home],['watch','Watch & Earn',PlayCircle],['rewards','Rewards',Gift],['leaderboard','Leaderboard',Trophy],['profile','Profile',UserRound]];
 function startAd(ad){if(state.watched.includes(ad.id)){setToast('This ad is already completed today.');return}setActiveAd(ad.id);setTime(ad.duration)}
 function submitGiveaway(e){e.preventDefault();if(state.watched.length<10){setToast('Complete all 10 daily ads to become eligible.');return}setState(s=>({...s,giveawayEntries:[{...form,date:new Date().toLocaleString(),status:'Eligible — entry saved'},...s.giveawayEntries]}));setShowGiveaway(false);setToast('Giveaway entry saved successfully.');}
 function resetDemo(){setState(defaultState);setToast('Demo activity reset.')}
 return <div className="app">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="logo">V</div><div><b>VELOOP</b><span>Rewards Giveaways</span></div></div><div className="sideNav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><Icon size={19}/><span>{label}</span>{id==='rewards'&&<em>NEW</em>}</button>)}</div><div className="sideBottom"><button onClick={()=>setPage('how')}><Info size={18}/>How It Works</button><button onClick={()=>setPage('safety')}><ShieldCheck size={18}/>Eligibility & Safety</button><div className="miniUser"><div className="avatar">VP</div><div><b>Veloop Member</b><small>Level {Math.floor(state.balance/1000)+1} • Active</small></div></div></div></aside>
  <main className="main"><header><button className="menuBtn" onClick={()=>setMenu(!menu)}><Menu/></button><div className="crumb">{page==='dashboard'?'Overview':page==='watch'?'Watch & Earn':page[0].toUpperCase()+page.slice(1)}</div><div className="headerActions"><button className="iconBtn"><Bell size={19}/><i/></button><button className="balanceBtn"><WalletCards size={18}/><span>{state.balance.toLocaleString()} VE</span><ChevronDown size={15}/></button></div></header>
  <section className="content">
   {page==='dashboard'&&<Dashboard state={state} earnedToday={earnedToday} progress={progress} setPage={setPage} showGiveaway={()=>setShowGiveaway(true)} />}
   {page==='watch'&&<Watch ads={ADS} state={state} startAd={startAd} progress={progress} earnedToday={earnedToday}/>} 
   {page==='rewards'&&<Rewards state={state} setState={setState} toast={setToast}/>} 
   {page==='leaderboard'&&<Leaderboard state={state}/>} 
   {page==='profile'&&<Profile state={state} resetDemo={resetDemo}/>} 
   {page==='how'&&<InfoPage title="How It Works" icon={<Info/>}><Step n="01" title="Pick an available ad" text="Choose any ad card and start the short viewing timer."/><Step n="02" title="Complete the timer" text="Keep the ad open until the timer reaches zero. Closing the viewer cancels the session."/><Step n="03" title="Get the listed reward" text="After completion, the exact reward shown on the card is added to your demo wallet."/><Step n="04" title="Build your daily target" text="Complete 10 ads to finish the daily target and unlock giveaway eligibility."/></InfoPage>}
   {page==='safety'&&<InfoPage title="Eligibility & Safety" icon={<ShieldCheck/>}><div className="notice"><ShieldCheck/><div><b>Transparent demo rules</b><p>Rewards shown in this project are demo VE credits. Any real-money payout would require a secure backend, verified terms, payment provider and legal eligibility checks.</p></div></div><Step n="✓" title="One completion per ad per day" text="Completed ads are stored locally so refresh does not duplicate rewards."/><Step n="✓" title="Daily target: 10 ads" text="The target and progress are based on the actual completed-ad activity."/><Step n="✓" title="Giveaway eligibility" text="The entry form checks the 10-ad target before saving an entry."/></InfoPage>}
  </section></main>
  {activeAd!==null&&<AdModal ad={ADS.find(a=>a.id===activeAd)} time={time} onClose={()=>{setActiveAd(null);setTime(0);setToast('Ad session cancelled — no reward added.')}}/>}
  {showGiveaway&&<GiveawayModal form={form} setForm={setForm} submit={submitGiveaway} close={()=>setShowGiveaway(false)} eligible={progress>=10}/>} 
  {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}
function Dashboard({state,earnedToday,progress,setPage,showGiveaway}){return <>
 <div className="hero"><div><span className="eyebrow"><Spark/> DAILY REWARD HUB</span><h1>Turn your time into <span>reward progress.</span></h1><p>Watch short ads, complete your daily target, grow your VE balance and unlock giveaway opportunities.</p><div className="heroBtns"><button className="primary" onClick={()=>setPage('watch')}><Play size={17}/> Start Watching <ArrowUpRight size={16}/></button><button className="ghost" onClick={()=>setPage('how')}>How it works</button></div></div><div className="heroVisual"><div className="orb o1"/><div className="orb o2"/><div className="phone"><div className="phoneTop">VELOOP <span>● ●</span></div><div className="phoneCard"><img src={ADS[0].image}/><b>Watch & Earn</b><strong>+20 VE</strong><small>30 sec • Ready</small></div><div className="phoneStats"><div><b>{state.balance.toLocaleString()}</b><small>Wallet VE</small></div><div><b>{progress}/10</b><small>Today</small></div></div></div></div></div>
 <div className="stats"><Stat icon={<WalletCards/>} label="Total balance" value={`${state.balance.toLocaleString()} VE`} meta="Available demo credits"/><Stat icon={<Flame/>} label="Daily streak" value={`${state.streak} days`} meta="Keep your routine going"/><Stat icon={<Target/>} label="Today's target" value={`${progress}/10`} meta={`${earnedToday} VE earned today`}/><Stat icon={<Trophy/>} label="Your rank" value={`#${Math.max(1,12-state.watched.length)}`} meta="Activity-based demo rank"/></div>
 <div className="quickActions"><QuickAction icon={<WalletCards/>} title="Wallet & Withdraw" text="View balance and request a demo withdrawal claim" onClick={()=>setPage('rewards')}/><QuickAction icon={<Info/>} title="Report an Issue" text="Send wallet, ad or reward issue information" onClick={()=>setPage('safety')}/><QuickAction icon={<History/>} title="Transaction History" text="See your latest VE activity and claims" onClick={()=>setPage('rewards')}/></div>
 <div className="sectionHead"><div><span className="eyebrow">YOUR ROUTINE</span><h2>Today’s progress</h2></div><button className="textBtn" onClick={()=>setPage('watch')}>View all ads <ArrowUpRight size={16}/></button></div>
 <div className="progressPanel"><div className="ring" style={{'--p':`${progress*10}%`}}><div><b>{progress}</b><span>/ 10</span></div></div><div className="progressCopy"><h3>{progress===10?'Daily target complete!':'Complete 10 ads today'}</h3><p>{progress===10?'You unlocked giveaway eligibility.':'Stay consistent to unlock the giveaway entry and build your earning history.'}</p><div className="bar"><i style={{width:`${progress*10}%`}}/></div><small>{progress} of 10 ads completed • {10-progress} remaining</small></div><button className={progress===10?'successBtn':'primary'} onClick={progress===10?showGiveaway:()=>setPage('watch')}>{progress===10?<><Gift size={17}/> Enter Giveaway</>:<><Play size={17}/> Continue</>}</button></div>
 <div className="sectionHead"><div><span className="eyebrow">FEATURED</span><h2>Watch & Earn</h2></div></div><div className="adGrid">{ADS.slice(0,3).map(a=><AdCard key={a.id} ad={a} done={state.watched.includes(a.id)} onStart={()=>setPage('watch')}/>)}</div>
 </>}
function Spark(){return <Star size={13} fill="currentColor"/>} function Stat({icon,label,value,meta}){return <div className="stat"><div className="statIcon">{icon}</div><div><small>{label}</small><b>{value}</b><span>{meta}</span></div></div>} function QuickAction({icon,title,text,onClick}){return <button className="quickAction" onClick={onClick}><span className="quickIcon">{icon}</span><span><b>{title}</b><small>{text}</small></span><ArrowUpRight size={17}/></button> }
function Watch({ads,state,startAd,progress,earnedToday}){return <><div className="pageTitle"><div><span className="eyebrow">WATCH & EARN</span><h1>Choose an ad. Complete it. Earn the listed VE.</h1><p>Every card has its own duration and reward. Your progress is saved in this browser.</p></div><div className="targetBadge"><Target/><b>{progress}/10</b><span>daily target</span></div></div><div className="earnBanner"><div><b>{earnedToday} VE</b><span>earned today</span></div><div className="bannerLine"><i style={{width:`${progress*10}%`}}/></div><div><b>{10-progress}</b><span>ads left</span></div></div><div className="adGrid full">{ads.map(a=><AdCard key={a.id} ad={a} done={state.watched.includes(a.id)} onStart={()=>startAd(a)}/>)}</div></>}
function AdCard({ad,done,onStart}){return <article className="adCard"><div className="adImg"><img src={ad.image}/><span className="brandPill">{ad.brand}</span>{done&&<div className="done"><CheckCircle2/> Completed</div>}</div><div className="adBody"><div className="adTitle"><div><h3>{ad.title}</h3><p><Clock3 size={14}/>{ad.duration}s viewing</p></div><strong>+{ad.reward} <small>VE</small></strong></div><button className={done?'disabled':'primary'} disabled={done} onClick={onStart}>{done?<><CheckCircle2 size={16}/> Completed</>:<><Play size={16}/> Watch Ad</>}</button></div></article>}
function AdModal({ad,time,onClose}){if(!ad)return null;return <div className="overlay"><div className="modal adModal"><button className="close" onClick={onClose}><X/></button><img className="modalImg" src={ad.image}/><div className="modalContent"><span className="brandPill">{ad.brand}</span><h2>{ad.title}</h2><p>Keep this viewer open until the timer completes to receive the listed reward.</p><div className="timer"><div className="timerCircle" style={{"--timerProgress":`${Math.max(0,Math.min(100,(time/ad.duration)*100))}%`}}><div className="timerInner"><b>{time}</b><span>sec</span></div></div><div><b>Reward +{ad.reward} VE</b><small>Completion will add the exact card reward.</small><div className="timerHint">Blue ring decreases every second</div></div></div><div className="bar"><i style={{width:`${Math.max(0,(1-time/ad.duration)*100)}%`}}/></div><button className="cancelBtn" onClick={onClose}>Cancel viewing</button></div></div></div>}
function Rewards({state,setState,toast}){const canRedeem=state.balance>=1000;function claim(){if(!canRedeem){toast('Demo redeem unlocks at 1,000 VE.');return}setState(s=>({...s,balance:s.balance-1000,claims:s.claims+1,history:[{id:Date.now(),text:'Reward claim requested',amount:-1000,date:new Date().toLocaleString()},...s.history]}));toast('Reward claim recorded in demo history.')}return <><div className="pageTitle"><div><span className="eyebrow">REWARDS WALLET</span><h1>Your progress, wallet and claims.</h1><p>Track VE credits, milestones and claim history in one place.</p></div><div className="walletHero"><WalletCards/><b>{state.balance.toLocaleString()} VE</b><span>current balance</span></div></div><div className="rewardGrid"><div className="walletCard"><div className="walletTop"><span>VELOOP WALLET</span><LockKeyhole size={16}/></div><b>{state.balance.toLocaleString()} VE</b><p>Demo balance from completed activities</p><div className="walletActions"><button className="primary" onClick={claim}><IndianRupee size={16}/> Request claim</button><button className="ghost"><History size={16}/> History</button></div></div><div className="milestone"><Target/><h3>Next milestone</h3><b>{Math.max(0,5000-state.balance).toLocaleString()} VE</b><p>more VE to reach the 5,000 VE milestone.</p><div className="bar"><i style={{width:`${Math.min(100,state.balance/50)}%`}}/></div></div></div><div className="sectionHead"><div><span className="eyebrow">ACTIVITY</span><h2>Recent transactions</h2></div></div><div className="history">{state.history.length?state.history.slice(0,8).map(h=><div className="historyRow" key={h.id}><div className="historyIcon">{h.amount>0?<Plus/>:<ArrowUpRight/>}</div><div><b>{h.text}</b><small>{h.date}</small></div><strong className={h.amount>0?'plus':''}>{h.amount>0?'+':''}{h.amount} VE</strong></div>):<div className="empty">No activity yet. Start watching ads to build your history.</div>}</div></>}
function Leaderboard({state}){const rows=[['You',state.watched.length*20+state.balance/100,'You','https://i.pravatar.cc/160?img=47'],['Aarav',1640,'Top activity','https://i.pravatar.cc/160?img=12'],['Meera',1510,'Consistent','https://i.pravatar.cc/160?img=32'],['Kabir',1320,'Active','https://i.pravatar.cc/160?img=15'],['Riya',1180,'Rising','https://i.pravatar.cc/160?img=44']].sort((a,b)=>b[1]-a[1]);const podium=rows.slice(0,3);return <><div className="pageTitle"><div><span className="eyebrow">LEADERBOARD</span><h1>Activity-based rankings.</h1><p>See the top 3 in a premium podium view, followed by the live activity list.</p></div><div className="streak"><Flame/><b>{state.streak}</b><span>day streak</span></div></div><div className="podium">{podium.map((r,i)=><div className={`podiumCard place-${i+1}`} key={r[0]}><div className="podiumGlow"/><div className="crown">{i===0?'♛':i===1?'◆':'✦'}</div><div className="podiumAvatar"><img src={r[3]} alt=""/><span>#{i+1}</span></div><b className="podiumName">{r[0]}</b><small>{r[2]}</small><strong>{Math.round(r[1]).toLocaleString()} <em>pts</em></strong><div className="podiumBase">{i===0?'WINNER':i===1?'RUNNER UP':'TOP 3'}</div></div>)}</div><div className="leaderCard"><div className="leaderHead"><span>Rank</span><span>Member</span><span>Activity points</span></div>{rows.slice(3).map((r,i)=><div className={r[0]==='You'?'leaderRow you':'leaderRow'} key={r[0]}><b>#{i+4}</b><div className="member"><div className="rankAvatar photo"><img src={r[3]} alt=""/></div><div><b>{r[0]}</b><small>{r[2]}</small></div></div><strong>{Math.round(r[1]).toLocaleString()}</strong></div>)}</div><div className="giveawayCard"><div><Gift size={30}/><span className="eyebrow">WINNER GIFT</span><h2>Reach today’s target and unlock the giveaway entry.</h2><p>Winner delivery details are collected only after eligibility is confirmed.</p></div><div className="giftVisual">🎁</div></div></>}
function Profile({state,resetDemo}){return <><div className="pageTitle"><div><span className="eyebrow">PROFILE</span><h1>Your Veloop account.</h1><p>Account activity, preferences and saved progress.</p></div><button className="ghost" onClick={resetDemo}><RefreshCw size={16}/> Reset demo</button></div><div className="profileGrid"><div className="profileCard"><div className="bigAvatar">VP</div><h2>Veloop Member</h2><p>Active rewards account</p><div className="profileStats"><div><b>{state.balance.toLocaleString()}</b><small>VE balance</small></div><div><b>{state.watched.length}</b><small>Ads completed</small></div><div><b>{state.claims}</b><small>Claims</small></div></div></div><div className="settingsCard"><h3><Settings/> Account settings</h3><div className="setting"><div><b>Notifications</b><small>Reward and activity alerts</small></div><div className="toggle on"/></div><div className="setting"><div><b>Daily target</b><small>10 ads per day</small></div><Target size={18}/></div><div className="setting"><div><b>Security</b><small>Local demo storage enabled</small></div><ShieldCheck size={18}/></div></div></div></>}
function InfoPage({title,icon,children}){return <><div className="pageTitle"><div><span className="eyebrow">VELOOP GUIDE</span><h1>{title}</h1><p>Everything you need to understand the reward flow.</p></div><div className="titleIcon">{icon}</div></div><div className="steps">{children}</div></>}
function Step({n,title,text}){return <div className="step"><div className="stepNum">{n}</div><div><h3>{title}</h3><p>{text}</p></div><CheckCircle2/></div>}
function GiveawayModal({form,setForm,submit,close,eligible}){return <div className="overlay"><form className="modal formModal" onSubmit={submit}><button type="button" className="close" onClick={close}><X/></button><span className="eyebrow">GIVEAWAY ENTRY</span><h2>Winner gift delivery details</h2><p>Eligibility is checked before the entry is saved.</p>{eligible?<div className="eligible"><BadgeCheck/> Eligible — 10/10 daily target completed</div>:<div className="notEligible"><Info/> Complete all 10 ads first.</div>}<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Delivery address<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><button className="primary" disabled={!eligible}><Send size={16}/> Save entry</button></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
